name: Build All
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        version:
          - { dir: Auto32k}
          - { dir: AutoCat}
          - { dir: FutureGui}
          - { dir: HitboxDesync}
          - { dir: MioClientGui}
          - { dir: PhobosGui}
    uses: 3arthh4ckDevelopment/3arthh4ck-Plugins/.github/workflows/build-plugin.yml@1.12.2
    with:
      dir: ${{ matrix.version.dir }}