name: Build All
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        version:
          - { dir: FutureGui }
          - { dir: VoiceControl }
          - { dir: Lawnmower }
    uses: 3arthh4ckDevelopment/3arthh4ck-Plugins/.github/workflows/build-plugin.yml@1.13+
    with:
      dir: ${{ matrix.version.dir }}